/**
 * Threat Intelligence & Defense Playbook Engine
 * Powers Dark Web Monitoring, Geopolitical Threat Context, YARA/Sigma/Snort Playbook Generation, and EPSS Vulnerability Matrix.
 */

// 1. Dark Web & Digital Risk Monitoring Data
export const MOCK_DARK_WEB_LEAKS = [
  {
    id: 'DW-8821',
    timestamp: '12 mins ago',
    source: 'BreachForums / Russian Market',
    category: 'Employee Credentials',
    severity: 'CRITICAL',
    title: 'Executive Email Credentials (CEO & CFO Hash Dump)',
    details: 'Corporate SSO credentials found in RedLine Stealer log bundle.',
    affectedAsset: 'john.smith@cybershield.io',
    remediation: 'Force immediate password reset & revoke active OAuth session tokens.'
  },
  {
    id: 'DW-8819',
    timestamp: '45 mins ago',
    source: 'GitHub Public Gist Paste',
    category: 'Source Code Leak',
    severity: 'HIGH',
    title: 'AWS Secret Access Key exposed in public commit',
    details: 'Production S3 bucket read/write token leaked in deployment script.',
    affectedAsset: 'AKIAIOSFODNN7EXAMPLE',
    remediation: 'Deactivate IAM Key immediately & rotate AWS root secrets.'
  },
  {
    id: 'DW-8812',
    timestamp: '2 hours ago',
    source: 'Exploit.in Underground Forum',
    category: 'Brand Mention',
    severity: 'MEDIUM',
    title: 'Initial Access Broker offering RDP access to Partner VPN',
    details: 'Broker selling access to sub-contractor active directory environment ($2,500).',
    affectedAsset: 'vpn.partner-vendor.com',
    remediation: 'Enable IP whitelisting on VPN gateway and audit contractor accounts.'
  },
  {
    id: 'DW-8805',
    timestamp: '5 hours ago',
    source: 'Telegram Channel (CyberArmyofRussia)',
    category: 'DDoS Planning',
    severity: 'HIGH',
    title: 'Target list published for financial web portals',
    details: 'Hacktivist channel mobilizing botnet for SYN-flood against public API endpoints.',
    affectedAsset: 'api.cybershield.io',
    remediation: 'Engage Cloudflare / AWS Shield DDoS mitigation rules & rate limiting.'
  }
];

// 2. Geopolitical & Physical Threat Context Data
export const GEOPOLITICAL_EVENTS = [
  {
    id: 'GEO-101',
    region: 'Eastern Europe / Baltic Region',
    actorGroup: 'Killnet / NoName57(16)',
    threatType: 'DDoS & Critical Infrastructure Disruption',
    riskLevel: 'HIGH',
    summary: 'Targeted DDoS campaigns against energy and banking sectors following diplomatic sanctions.',
    impactedOffices: ['Warsaw, Poland', 'Frankfurt, Germany'],
    recommendedAction: 'Increase BGP scrubbing center threshold and alert SOC tier-2 monitoring.'
  },
  {
    id: 'GEO-104',
    region: 'Middle East',
    actorGroup: 'MuddyWater / Cyber Av3ngers',
    threatType: 'ICS / SCADA & OT Network Probing',
    riskLevel: 'CRITICAL',
    summary: 'Exploitation of unpatched PLC web management portals across regional supply hubs.',
    impactedOffices: ['Dubai, UAE', 'Riyadh, Saudi Arabia'],
    recommendedAction: 'Isolate OT networks behind air-gapped industrial firewalls.'
  },
  {
    id: 'GEO-108',
    region: 'East Asia / Pacific',
    actorGroup: 'APT41 / Winnti Group',
    threatType: 'Supply Chain Code Injection',
    riskLevel: 'MEDIUM',
    summary: 'Spear-phishing targeting IT service provider updates in software tech hubs.',
    impactedOffices: ['Singapore', 'Tokyo, Japan'],
    recommendedAction: 'Mandate SHA-256 binary signing checks on third-party software updates.'
  }
];

// 3. Automated Playbook Generator (YARA, Sigma, Snort)
export function generateYaraRule(ruleName, iocString) {
  const cleanName = ruleName.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase() || 'threat_detection_rule';
  const iocClean = iocString || 'malicious_payload_string';

  return `rule Apt_${cleanName} {
    meta:
        description = "Automated YARA rule generated by Aegis CyberSentinel"
        author = "Aegis AI Playbook Engine"
        date = "${new Date().toISOString().split('T')[0]}"
        severity = "CRITICAL"
        threat_category = "Malware / Exploit Payload"
    strings:
        $header = { 4D 5A 90 00 03 00 00 00 } // PE Executable Header
        $ioc1 = "${iocClean}" ascii wide nocase
        $c2_domain = "malicious-c2-beacon.org" ascii wide
        $eval_func = "VirtualAllocEx" ascii
    condition:
        $header at 0 and ($ioc1 or $c2_domain) and $eval_func
}`;
}

export function generateSigmaRule(ruleName, iocString) {
  const cleanName = ruleName || 'Suspicious Process Execution';
  return `title: ${cleanName}
id: ${Math.random().toString(36).substring(2, 10)}-sigma-auto
status: experimental
description: Auto-generated Sigma detection rule for EDR / SIEM integration.
author: Aegis Playbook Generator
date: ${new Date().toISOString().split('T')[0]}
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        CommandLine|contains:
            - '${iocString || 'powershell -Enc'}'
            - 'cmd.exe /c echo'
            - 'vssadmin delete shadows'
    condition: selection
falsepositives:
    - Administrative maintenance scripts
level: high`;
}

export function generateSnortRule(ruleName, iocString) {
  const ipOrDomain = iocString || 'malicious-domain.com';
  return `# Snort 3 Firewall Rule
alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (
    msg:"AEGIS-SENTINEL Block ${ruleName || 'Malicious Outbound Request'}";
    flow:established,to_server;
    content:"${ipOrDomain}"; http_host;
    classtype:trojan-activity;
    sid:1009841;
    rev:1;
)`;
}

// 4. Vulnerability Prioritization Matrix (EPSS vs CVSS)
export const VULNERABILITY_MATRIX_DATA = [
  {
    cve: 'CVE-2026-21482',
    software: 'Apache Struts 2 RCE',
    cvssScore: 9.8,
    epssScore: 0.942, // 94.2% probability of exploit in next 30 days
    cisaKev: true, // Known Exploited Vulnerability
    weaponizedState: 'Active Ransomware Exploitation in Wild',
    patchStatus: 'Patch Available (v2.5.33)',
    priority: 'CRITICAL (P1)'
  },
  {
    cve: 'CVE-2026-1904',
    software: 'OpenSSL Memory Leak',
    cvssScore: 9.1,
    epssScore: 0.124, // High CVSS, but low EPSS exploitability
    cisaKev: false,
    weaponizedState: 'Proof of Concept Only (Lab environment)',
    patchStatus: 'Patch Available (v3.2.1)',
    priority: 'MEDIUM (P3)'
  },
  {
    cve: 'CVE-2026-30411',
    software: 'Fortinet FortiOS Auth Bypass',
    cvssScore: 9.6,
    epssScore: 0.887,
    cisaKev: true,
    weaponizedState: 'Mass Scanning & Botnet Integration',
    patchStatus: 'Critical Hotfix Available',
    priority: 'CRITICAL (P1)'
  },
  {
    cve: 'CVE-2025-48901',
    software: 'Spring Framework Deserialization',
    cvssScore: 7.5,
    epssScore: 0.765, // Low CVSS but High real-world EPSS!
    cisaKev: true,
    weaponizedState: 'Active In-the-Wild Exploitation',
    patchStatus: 'Patch Available (v6.1.4)',
    priority: 'HIGH (P2)'
  }
];
